### PR TITLE
Handle API Key gracefully (Issue #3)

### PR DESCRIPTION
**Pull request by ionescu77**
This will display a nice error message in the frontend that Hugginface API Key is not set

### CODE REVIEW

**Comment by ionescu77** [comment]
Screenshot 2024-09-23 at 11 39 37

**Review by alexmazaltov — COMMENTED** [review]
@ionescu77 How did you managed to fix code styles cause in my computer at some point of time cursor started to mark all code with red underscore lines....

image


I think there should be some technic that I missing for auto fix such issue

**Review by alexmazaltov — APPROVED** [review]
@ionescu77 How did you managed to fix code styles cause in my computer at some point of time cursor started to mark all code with red underscore lines....

image


I think there should be some technic that I missing for auto fix such issue

**Comment by ionescu77** [comment]
> @ionescu77 How did you managed to fix code styles cause in my computer at some point of time cursor started to mark all code with red underscore lines....
> 
> image
> 
> I think there should be some technic that I missing for auto fix such issue

Alex I am using [Zed Editor](https://zed.dev/) - from the funders of Atom Editor (which is not maintained anymor).

It is formating code automatically, it is fast writen in Rust and introduced AI assistant (but sometimes Cursor is easier)

**Pull request merged**
